// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: scanner.flex

/* User code section */


@SuppressWarnings("fallthrough")
public class Yylex {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int COMMENT = 2;
  public static final int STRING = 4;
  public static final int CHARLIT = 6;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1,  1,  2,  2,  3, 3
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\2\3\1\2\22\0\1\1\1\4"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\2\13\1\14"+
    "\1\15\1\13\1\16\1\17\1\4\12\20\2\13\1\4"+
    "\1\21\1\4\2\0\1\22\1\23\1\24\1\25\1\26"+
    "\1\27\1\30\1\31\1\32\1\30\1\33\1\34\1\30"+
    "\1\35\1\36\1\37\1\30\1\40\1\41\1\42\1\43"+
    "\5\30\1\13\1\44\1\13\1\0\1\45\1\0\1\46"+
    "\1\47\1\50\1\51\1\52\1\53\1\54\1\55\1\56"+
    "\1\54\1\57\1\60\1\54\1\61\1\62\1\63\1\54"+
    "\1\64\1\65\1\66\1\67\5\54\1\13\1\70\1\13"+
    "\7\0\1\3\u01a2\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\4\0\1\1\1\2\1\3\1\4\2\1\1\3\1\1"+
    "\1\5\1\6\3\3\1\7\13\10\14\1\3\11\1\12"+
    "\1\13\1\14\1\0\1\15\1\16\1\12\1\17\1\20"+
    "\2\0\1\7\1\0\1\10\1\0\1\10\6\0\1\1"+
    "\5\0\7\1\1\10\6\1\1\21\1\22\1\23\1\24"+
    "\1\25\1\26\1\27\1\0\1\30\1\31\1\10\1\0"+
    "\1\10\13\0\14\1\2\0\1\31\1\0\1\10\1\0"+
    "\1\10\4\0\1\1\5\0\10\1\1\32\1\0\1\1"+
    "\1\31\1\0\1\31\1\10\1\0\1\10\1\1\7\0"+
    "\5\1\1\0\1\31\1\10\1\0\1\10\3\0\1\1"+
    "\1\0\2\1\1\31\1\10\1\0\1\10\2\0\1\1"+
    "\1\0\1\31\1\10\1\0\1\10\1\0\1\1\1\10"+
    "\1\0\1\10\1\1\1\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\1\0\2\10\1\0\2\10"+
    "\1\0\2\10\1\0\2\10\1\0\1\10\1\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\253\0\344\0\u011d\0\u0156\0\344"+
    "\0\u018f\0\u01c8\0\344\0\u0201\0\u023a\0\344\0\u0273\0\u02ac"+
    "\0\u02e5\0\u031e\0\u0357\0\u0390\0\u03c9\0\u0402\0\u043b\0\u0474"+
    "\0\u04ad\0\u04e6\0\u051f\0\u0558\0\u0591\0\u05ca\0\u0603\0\u063c"+
    "\0\u0675\0\u06ae\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804"+
    "\0\u083d\0\344\0\u0876\0\u08af\0\344\0\344\0\344\0\u08e8"+
    "\0\344\0\344\0\u0921\0\u095a\0\344\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\u0b22\0\u0b5b\0\u0b94\0\u0bcd"+
    "\0\u0c06\0\u0c3f\0\u0ab0\0\u0c78\0\u0cb1\0\u0cea\0\u0d23\0\u0d5c"+
    "\0\u0d95\0\u0dce\0\u0e07\0\u0e40\0\u0e79\0\u0eb2\0\u0eeb\0\u01c8"+
    "\0\u0f24\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\u1041\0\344\0\344"+
    "\0\344\0\344\0\344\0\344\0\344\0\u107a\0\344\0\u10b3"+
    "\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u1242\0\u127b"+
    "\0\u12b4\0\u12ed\0\u1326\0\u135f\0\u1398\0\u13d1\0\u140a\0\u1443"+
    "\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599\0\u15d2\0\u160b"+
    "\0\u1644\0\u167d\0\u16b6\0\u16ef\0\u1728\0\u1761\0\u179a\0\u17d3"+
    "\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0\0\u17d3\0\u1929\0\u1962"+
    "\0\u199b\0\u19d4\0\u1a0d\0\u1a46\0\u1a7f\0\u1ab8\0\u1af1\0\u1b2a"+
    "\0\u1b63\0\u1b9c\0\u1bd5\0\u01c8\0\u1c0e\0\u1c47\0\u1c80\0\u1cb9"+
    "\0\u1cf2\0\u1d2b\0\u1d64\0\u1d9d\0\u1d64\0\u1dd6\0\u1e0f\0\u1e48"+
    "\0\u1e81\0\u1eba\0\u1ef3\0\u1f2c\0\u1f65\0\u1f9e\0\u1fd7\0\u2010"+
    "\0\u2049\0\u2082\0\u20bb\0\u20f4\0\u212d\0\u2166\0\u219f\0\u21d8"+
    "\0\u2211\0\u212d\0\u224a\0\u2283\0\u22bc\0\u22f5\0\u232e\0\u2367"+
    "\0\u23a0\0\u23d9\0\u2412\0\u2367\0\u244b\0\u2484\0\u24bd\0\u24f6"+
    "\0\u252f\0\u2568\0\u24f6\0\u25a1\0\u25da\0\u2613\0\u25da\0\u264c"+
    "\0\u2685\0\u26be\0\u26f7\0\u2730\0\u2769\0\u27a2\0\u27db\0\u2814"+
    "\0\u284d\0\u2886\0\u28bf\0\u28f8\0\u2931\0\u296a\0\u29a3\0\u29dc"+
    "\0\u2a15\0\u2a4e\0\u2a87\0\u2ac0\0\u2af9\0\u2b32\0\u2b6b\0\u2ba4"+
    "\0\u2bdd\0\u2c16\0\u2c4f\0\u2c88\0\u2cc1\0\u2cfa\0\u2d33\0\u2d6c"+
    "\0\u2da5\0\u2dde\0\u2e17\0\u2e50\0\u2e89\0\u2ec2\0\u2efb\0\u2f34"+
    "\0\u2f6d\0\u2fa6\0\u2fdf\0\u3018\0\u3051\0\u308a\0\u30c3\0\u30fc"+
    "\0\u3135\0\u316e\0\u31a7\0\u31e0\0\u3219\0\u3252\0\u328b\0\u32c4"+
    "\0\u32fd\0\u3336\0\u336f\0\u33a8\0\u33e1\0\u341a\0\u01c8";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\5\2\6\1\0\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\5\1\22"+
    "\1\7\1\23\1\24\1\25\1\26\1\27\1\30\2\23"+
    "\1\31\1\23\1\32\1\23\1\33\1\23\1\34\1\35"+
    "\2\23\2\5\1\12\1\36\1\37\1\40\1\41\1\42"+
    "\2\12\1\43\1\12\1\44\1\12\1\45\1\12\1\46"+
    "\1\47\1\50\1\12\1\51\6\52\1\53\5\52\1\54"+
    "\54\52\2\55\1\56\2\55\1\57\36\55\1\60\26\55"+
    "\1\61\7\55\1\62\31\55\1\63\24\55\72\0\2\6"+
    "\107\0\1\13\55\0\1\64\5\0\1\65\74\0\1\12"+
    "\1\0\22\12\1\0\23\12\12\0\1\13\57\0\12\66"+
    "\1\0\31\66\1\67\24\66\14\0\1\13\4\0\1\13"+
    "\64\0\1\13\2\0\1\70\1\13\65\0\1\13\1\0"+
    "\1\70\1\13\66\0\1\71\1\22\1\0\22\12\2\0"+
    "\22\12\21\0\1\72\1\0\22\73\1\0\1\72\22\74"+
    "\21\0\1\72\1\0\16\73\1\75\3\73\1\0\1\72"+
    "\22\74\21\0\1\72\1\0\14\73\1\76\5\73\1\0"+
    "\1\72\22\74\21\0\1\72\1\0\4\73\1\77\15\73"+
    "\1\0\1\72\22\74\21\0\1\72\1\0\12\73\1\100"+
    "\7\73\1\0\1\72\22\74\21\0\1\72\1\0\10\73"+
    "\1\101\10\73\1\102\1\0\1\72\22\74\21\0\1\72"+
    "\1\0\5\73\1\103\5\73\1\104\6\73\1\0\1\72"+
    "\22\74\21\0\1\72\1\0\14\73\1\105\5\73\1\0"+
    "\1\72\22\74\21\0\1\72\1\0\21\73\1\106\1\0"+
    "\1\72\22\74\21\0\1\72\1\0\4\73\1\107\15\73"+
    "\1\0\1\72\22\74\21\0\1\72\1\0\20\73\1\110"+
    "\1\73\1\0\1\72\22\74\21\0\1\12\1\0\22\12"+
    "\1\0\17\12\1\111\3\12\21\0\1\12\1\0\22\12"+
    "\1\0\15\12\1\112\5\12\21\0\1\12\1\0\22\12"+
    "\1\0\5\12\1\113\15\12\21\0\1\12\1\0\22\12"+
    "\1\0\13\12\1\114\7\12\21\0\1\12\1\0\22\12"+
    "\1\0\1\12\1\115\7\12\1\116\10\12\1\117\21\0"+
    "\1\12\1\0\22\12\1\0\6\12\1\120\5\12\1\121"+
    "\6\12\21\0\1\12\1\0\22\12\1\0\15\12\1\122"+
    "\5\12\21\0\1\12\1\0\22\12\1\0\22\12\1\123"+
    "\21\0\1\12\1\0\22\12\1\0\5\12\1\124\15\12"+
    "\21\0\1\12\1\0\22\12\1\0\21\12\1\125\1\12"+
    "\21\0\1\12\1\0\22\12\1\0\17\12\1\126\3\12"+
    "\71\0\1\13\14\0\1\127\62\0\1\130\67\0\1\131"+
    "\36\0\1\132\14\0\1\133\2\0\1\134\1\0\1\135"+
    "\1\136\13\0\1\55\31\0\1\55\14\0\1\55\2\0"+
    "\1\55\1\0\1\55\2\0\2\64\1\0\66\64\12\0"+
    "\1\137\70\0\1\66\31\0\1\66\14\0\1\66\2\0"+
    "\1\66\1\0\1\66\21\0\1\71\1\70\70\0\1\140"+
    "\70\0\1\141\1\0\22\142\1\0\23\141\21\0\1\142"+
    "\1\0\22\142\1\0\23\142\21\0\1\141\1\0\22\12"+
    "\1\0\1\141\22\143\21\0\1\142\1\0\4\142\1\144"+
    "\15\142\1\0\23\142\21\0\1\142\1\0\13\142\1\145"+
    "\6\142\1\0\23\142\21\0\1\142\1\0\2\142\1\146"+
    "\17\142\1\0\23\142\21\0\1\142\1\0\17\142\1\147"+
    "\2\142\1\0\23\142\21\0\1\142\1\0\13\142\1\150"+
    "\6\142\1\0\23\142\21\0\1\142\1\0\13\142\1\151"+
    "\6\142\1\0\23\142\21\0\1\142\1\0\15\142\1\152"+
    "\4\142\1\0\23\142\21\0\1\142\1\0\14\142\1\153"+
    "\5\142\1\0\23\142\21\0\1\142\1\0\20\142\1\154"+
    "\1\142\1\0\23\142\21\0\1\142\1\0\20\142\1\155"+
    "\1\142\1\0\23\142\21\0\1\142\1\0\1\156\21\142"+
    "\1\0\23\142\21\0\1\12\1\0\22\12\1\0\5\12"+
    "\1\157\15\12\21\0\1\12\1\0\22\12\1\0\14\12"+
    "\1\160\6\12\21\0\1\12\1\0\22\12\1\0\3\12"+
    "\1\161\17\12\21\0\1\12\1\0\22\12\1\0\20\12"+
    "\1\162\2\12\21\0\1\12\1\0\22\12\1\0\13\12"+
    "\1\163\7\12\21\0\1\12\1\0\22\12\1\0\14\12"+
    "\1\164\6\12\21\0\1\12\1\0\22\12\1\0\14\12"+
    "\1\165\6\12\21\0\1\12\1\0\22\12\1\0\16\12"+
    "\1\166\4\12\21\0\1\12\1\0\22\12\1\0\15\12"+
    "\1\167\5\12\21\0\1\12\1\0\22\12\1\0\21\12"+
    "\1\121\1\12\21\0\1\12\1\0\22\12\1\0\21\12"+
    "\1\170\1\12\21\0\1\12\1\0\22\12\1\0\1\12"+
    "\1\171\21\12\21\0\1\12\1\0\22\12\1\0\22\12"+
    "\1\172\21\0\1\173\1\0\6\173\16\0\6\173\34\0"+
    "\1\174\1\175\5\0\1\176\23\0\1\176\36\0\1\177"+
    "\1\0\22\200\1\0\23\177\21\0\1\200\1\0\22\200"+
    "\1\0\23\200\21\0\1\177\1\0\22\12\1\0\1\177"+
    "\22\201\21\0\1\200\1\0\1\202\21\200\1\0\23\200"+
    "\21\0\1\200\1\0\3\200\1\203\14\200\1\204\1\200"+
    "\1\0\23\200\21\0\1\200\1\0\12\200\1\205\7\200"+
    "\1\0\23\200\21\0\1\200\1\0\4\200\1\206\15\200"+
    "\1\0\23\200\21\0\1\200\1\0\10\200\1\207\11\200"+
    "\1\0\23\200\21\0\1\200\1\0\2\200\1\210\17\200"+
    "\1\0\23\200\21\0\1\200\1\0\21\200\1\211\1\0"+
    "\23\200\21\0\1\200\1\0\15\200\1\206\4\200\1\0"+
    "\23\200\21\0\1\200\1\0\15\200\1\212\4\200\1\0"+
    "\23\200\21\0\1\200\1\0\21\200\1\213\1\0\23\200"+
    "\21\0\1\200\1\0\16\200\1\211\3\200\1\0\23\200"+
    "\21\0\1\12\1\0\22\12\1\0\1\12\1\214\21\12"+
    "\21\0\1\12\1\0\22\12\1\0\4\12\1\215\14\12"+
    "\1\216\1\12\21\0\1\12\1\0\22\12\1\0\13\12"+
    "\1\217\7\12\21\0\1\12\1\0\22\12\1\0\5\12"+
    "\1\120\15\12\21\0\1\12\1\0\22\12\1\0\20\12"+
    "\1\172\2\12\21\0\1\12\1\0\22\12\1\0\11\12"+
    "\1\220\11\12\21\0\1\12\1\0\22\12\1\0\3\12"+
    "\1\221\17\12\21\0\1\12\1\0\22\12\1\0\22\12"+
    "\1\222\21\0\1\12\1\0\22\12\1\0\16\12\1\120"+
    "\4\12\21\0\1\12\1\0\22\12\1\0\22\12\1\223"+
    "\21\0\1\12\1\0\22\12\1\0\17\12\1\222\3\12"+
    "\21\0\1\12\1\0\22\12\1\0\5\12\1\224\15\12"+
    "\21\0\1\225\1\0\6\225\16\0\6\225\35\0\1\226"+
    "\67\0\1\174\1\227\5\0\1\176\23\0\1\176\33\0"+
    "\2\230\1\0\1\231\70\0\1\232\1\0\22\233\1\0"+
    "\23\232\21\0\1\233\1\0\22\233\1\0\23\233\21\0"+
    "\1\232\1\0\22\12\1\0\1\232\22\234\21\0\1\233"+
    "\1\0\11\233\1\235\10\233\1\0\23\233\21\0\1\233"+
    "\1\0\10\233\1\236\11\233\1\0\23\233\21\0\1\233"+
    "\1\0\10\233\1\237\11\233\1\0\23\233\21\0\1\233"+
    "\1\0\1\240\21\233\1\0\23\233\21\0\1\233\1\0"+
    "\17\233\1\241\2\233\1\0\23\233\21\0\1\233\1\0"+
    "\20\233\1\242\1\233\1\0\23\233\21\0\1\233\1\0"+
    "\20\233\1\235\1\233\1\0\23\233\21\0\1\233\1\0"+
    "\21\233\1\243\1\0\23\233\21\0\1\233\1\0\16\233"+
    "\1\244\3\233\1\0\23\233\21\0\1\12\1\0\22\12"+
    "\1\0\12\12\1\120\10\12\21\0\1\12\1\0\22\12"+
    "\1\0\11\12\1\221\11\12\21\0\1\12\1\0\22\12"+
    "\1\0\11\12\1\245\11\12\21\0\1\12\1\0\22\12"+
    "\1\0\1\12\1\246\21\12\21\0\1\12\1\0\22\12"+
    "\1\0\20\12\1\247\2\12\21\0\1\12\1\0\22\12"+
    "\1\0\21\12\1\250\1\12\21\0\1\12\1\0\22\12"+
    "\1\0\21\12\1\120\1\12\21\0\1\12\1\0\22\12"+
    "\1\0\17\12\1\251\3\12\21\0\1\252\1\0\6\252"+
    "\16\0\6\252\34\0\1\174\1\226\67\0\1\174\1\253"+
    "\5\0\1\176\23\0\1\176\36\0\1\231\67\0\1\174"+
    "\1\231\70\0\1\254\1\0\22\255\1\0\23\254\21\0"+
    "\1\255\1\0\22\255\1\0\23\255\21\0\1\254\1\0"+
    "\22\12\1\0\1\254\22\256\21\0\1\255\1\0\20\255"+
    "\1\257\1\255\1\0\23\255\21\0\1\255\1\0\13\255"+
    "\1\260\6\255\1\0\23\255\21\0\1\255\1\0\16\255"+
    "\1\261\3\255\1\0\23\255\21\0\1\255\1\0\7\255"+
    "\1\262\12\255\1\0\23\255\21\0\1\255\1\0\10\255"+
    "\1\263\11\255\1\0\23\255\21\0\1\255\1\0\20\255"+
    "\1\262\1\255\1\0\23\255\21\0\1\255\1\0\13\255"+
    "\1\262\6\255\1\0\23\255\21\0\1\12\1\0\22\12"+
    "\1\0\14\12\1\264\6\12\21\0\1\12\1\0\22\12"+
    "\1\0\17\12\1\162\3\12\21\0\1\12\1\0\22\12"+
    "\1\0\10\12\1\120\12\12\21\0\1\12\1\0\22\12"+
    "\1\0\11\12\1\265\11\12\21\0\1\12\1\0\22\12"+
    "\1\0\14\12\1\120\6\12\21\0\1\55\1\0\6\55"+
    "\16\0\6\55\34\0\1\174\1\266\5\0\1\176\23\0"+
    "\1\176\36\0\1\267\1\0\22\270\1\0\23\267\21\0"+
    "\1\270\1\0\22\270\1\0\23\270\21\0\1\267\1\0"+
    "\22\12\1\0\1\267\22\271\21\0\1\270\1\0\10\270"+
    "\1\272\11\270\1\0\23\270\21\0\1\270\1\0\21\270"+
    "\1\273\1\0\23\270\21\0\1\270\1\0\4\270\1\274"+
    "\15\270\1\0\23\270\21\0\1\270\1\0\14\270\1\275"+
    "\5\270\1\0\23\270\21\0\1\12\1\0\22\12\1\0"+
    "\22\12\1\162\21\0\1\12\1\0\22\12\1\0\15\12"+
    "\1\251\5\12\20\0\1\174\1\276\5\0\1\176\23\0"+
    "\1\176\36\0\1\277\1\0\22\300\1\0\23\277\21\0"+
    "\1\300\1\0\22\300\1\0\23\300\21\0\1\277\1\0"+
    "\22\12\1\0\1\277\22\301\21\0\1\300\1\0\14\300"+
    "\1\302\5\300\1\0\23\300\21\0\1\300\1\0\4\300"+
    "\1\303\15\300\1\0\23\300\21\0\1\300\1\0\13\300"+
    "\1\303\6\300\1\0\23\300\20\0\1\174\6\0\1\176"+
    "\23\0\1\176\36\0\1\304\1\0\22\305\1\0\23\304"+
    "\21\0\1\305\1\0\22\305\1\0\23\305\21\0\1\304"+
    "\1\0\22\12\1\0\1\304\22\306\21\0\1\305\1\0"+
    "\13\305\1\307\6\305\1\0\23\305\21\0\1\310\1\0"+
    "\22\311\1\0\23\310\21\0\1\311\1\0\22\311\1\0"+
    "\23\311\21\0\1\310\1\0\22\12\1\0\1\310\22\312"+
    "\21\0\1\313\1\0\22\314\1\0\23\313\21\0\1\314"+
    "\1\0\22\314\1\0\23\314\21\0\1\313\1\0\22\12"+
    "\1\0\1\313\22\315\21\0\1\316\1\0\22\317\1\0"+
    "\23\316\21\0\1\317\1\0\22\317\1\0\23\317\21\0"+
    "\1\316\1\0\22\12\1\0\1\316\22\320\21\0\1\321"+
    "\1\0\22\322\1\0\23\321\21\0\1\322\1\0\22\322"+
    "\1\0\23\322\21\0\1\321\1\0\22\12\1\0\1\321"+
    "\22\323\21\0\1\324\1\0\22\325\1\0\23\324\21\0"+
    "\1\325\1\0\22\325\1\0\23\325\21\0\1\324\1\0"+
    "\22\12\1\0\1\324\22\326\21\0\1\327\1\0\22\330"+
    "\1\0\23\327\21\0\1\330\1\0\22\330\1\0\23\330"+
    "\21\0\1\327\1\0\22\12\1\0\1\327\22\331\21\0"+
    "\1\332\1\0\22\333\1\0\23\332\21\0\1\333\1\0"+
    "\22\333\1\0\23\333\21\0\1\332\1\0\22\12\1\0"+
    "\1\332\22\334\21\0\1\335\1\0\22\336\1\0\23\335"+
    "\21\0\1\336\1\0\22\336\1\0\23\336\21\0\1\335"+
    "\1\0\22\12\1\0\1\335\22\337\21\0\1\340\1\0"+
    "\22\341\1\0\23\340\21\0\1\341\1\0\22\341\1\0"+
    "\23\341\21\0\1\340\1\0\22\12\1\0\1\340\22\342"+
    "\21\0\1\343\1\0\22\344\1\0\23\343\21\0\1\344"+
    "\1\0\22\344\1\0\23\344\21\0\1\343\1\0\22\12"+
    "\1\0\1\343\22\345\21\0\1\346\1\0\22\347\1\0"+
    "\23\346\21\0\1\347\1\0\22\347\1\0\23\347\21\0"+
    "\1\346\1\0\22\12\1\0\1\346\22\350\21\0\1\351"+
    "\1\0\22\352\1\0\23\351\21\0\1\352\1\0\22\352"+
    "\1\0\23\352\21\0\1\351\1\0\22\12\1\0\1\351"+
    "\22\353\21\0\1\354\1\0\22\355\1\0\23\354\21\0"+
    "\1\355\1\0\22\355\1\0\23\355\21\0\1\354\1\0"+
    "\22\12\1\0\1\354\22\356\21\0\1\357\1\0\22\360"+
    "\1\0\23\357\21\0\1\360\1\0\22\360\1\0\23\360"+
    "\21\0\1\357\1\0\22\12\1\0\1\357\22\361\21\0"+
    "\1\362\1\0\22\363\1\0\23\362\21\0\1\363\1\0"+
    "\22\363\1\0\23\363\21\0\1\362\1\0\22\12\1\0"+
    "\1\362\22\364\21\0\1\365\1\0\22\366\1\0\23\365"+
    "\21\0\1\366\1\0\22\366\1\0\23\366\21\0\1\365"+
    "\1\0\22\12\1\0\1\365\22\367\21\0\1\370\1\0"+
    "\22\371\1\0\23\370\21\0\1\371\1\0\22\371\1\0"+
    "\23\371\21\0\1\370\1\0\22\12\1\0\1\370\22\372"+
    "\21\0\1\373\1\0\22\374\1\0\23\373\21\0\1\374"+
    "\1\0\22\374\1\0\23\374\21\0\1\373\1\0\22\12"+
    "\1\0\1\373\22\375\21\0\1\376\1\0\22\377\1\0"+
    "\23\376\21\0\1\377\1\0\22\377\1\0\23\377\21\0"+
    "\1\376\1\0\22\12\1\0\1\376\22\u0100\21\0\1\u0101"+
    "\1\0\22\u0102\1\0\23\u0101\21\0\1\u0102\1\0\22\u0102"+
    "\1\0\23\u0102\21\0\1\u0101\1\0\22\12\1\0\1\u0101"+
    "\22\u0103\21\0\1\u0104\1\0\22\u0105\1\0\23\u0104\21\0"+
    "\1\u0105\1\0\22\u0105\1\0\23\u0105\21\0\1\u0104\1\0"+
    "\22\12\1\0\1\u0104\22\u0106\21\0\1\120\1\0\22\u0107"+
    "\1\0\23\120\21\0\1\u0107\1\0\22\u0107\1\0\23\u0107"+
    "\21\0\1\120\1\0\22\12\1\0\23\120\1\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[13395];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\4\0\1\11\2\1\1\11\2\1\1\11\2\1\1\11"+
    "\33\1\1\11\2\1\3\11\1\0\2\11\2\1\1\11"+
    "\2\0\1\1\1\0\1\1\1\0\1\1\6\0\1\1"+
    "\5\0\16\1\7\11\1\0\1\11\2\1\1\0\1\1"+
    "\13\0\14\1\2\0\1\1\1\0\1\1\1\0\1\1"+
    "\4\0\1\1\5\0\11\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\7\0\5\1\1\0\2\1\1\0\1\1"+
    "\3\0\1\1\1\0\4\1\1\0\1\1\2\0\1\1"+
    "\1\0\2\1\1\0\1\1\1\0\2\1\1\0\3\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\1\1\1\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[263];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

private int commentDepth = 0;
private int commentStartLine = 0;
private StringBuilder stringBuffer = new StringBuilder();
private StringBuilder commentBuffer = new StringBuilder();
private boolean eofProcessed = false;

private Token token(TokenType type, String lexeme) {
    return new Token(type, lexeme, yyline + 1, yycolumn + 1);
}

private Token token(TokenType type, String lexeme, int endLine) {
    return new Token(type, lexeme, commentStartLine, 1, endLine);
}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Yylex(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            switch (zzLexicalState) {
            case COMMENT: {
              if (eofProcessed) {
        eofProcessed = false;
        return null;
    }
    eofProcessed = true;
    yybegin(YYINITIAL);
    int endLine = yyline + 1;
    return token(TokenType.ERROR, "Unterminated multi-line comment", endLine);
            }  // fall though
            case 264: break;
            case STRING: {
              yybegin(YYINITIAL);
    return token(TokenType.ERROR, "Unterminated string literal");
            }  // fall though
            case 265: break;
            case CHARLIT: {
              yybegin(YYINITIAL);
    return token(TokenType.ERROR, "Unclosed character literal");
            }  // fall though
            case 266: break;
            default:
        return null;
        }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { return token(TokenType.ERROR, yytext());
            }
          // fall through
          case 27: break;
          case 2:
            { /* skip */
            }
          // fall through
          case 28: break;
          case 3:
            { return token(TokenType.OPERATOR, yytext());
            }
          // fall through
          case 29: break;
          case 4:
            { stringBuffer.setLength(0);
    stringBuffer.append("\"");
    yybegin(STRING);
            }
          // fall through
          case 30: break;
          case 5:
            { stringBuffer.setLength(0);
    yybegin(CHARLIT);
            }
          // fall through
          case 31: break;
          case 6:
            { return token(TokenType.PUNCTUATOR, yytext());
            }
          // fall through
          case 32: break;
          case 7:
            { return token(TokenType.INTEGER_LITERAL, yytext());
            }
          // fall through
          case 33: break;
          case 8:
            { return token(TokenType.IDENTIFIER, yytext());
            }
          // fall through
          case 34: break;
          case 9:
            { commentBuffer.append(yytext());
            }
          // fall through
          case 35: break;
          case 10:
            { stringBuffer.append(yytext());
            }
          // fall through
          case 36: break;
          case 11:
            { yybegin(YYINITIAL);
    return token(TokenType.ERROR, "Unterminated string literal");
            }
          // fall through
          case 37: break;
          case 12:
            { stringBuffer.append("\"");
    yybegin(YYINITIAL);
    return token(TokenType.STRING_LITERAL, stringBuffer.toString());
            }
          // fall through
          case 38: break;
          case 13:
            { yybegin(YYINITIAL);
    return token(TokenType.ERROR, "Unclosed character literal");
            }
          // fall through
          case 39: break;
          case 14:
            { yybegin(YYINITIAL);
    return token(TokenType.ERROR, "MALFORMED_CHAR_LITERAL:" + stringBuffer.toString());
            }
          // fall through
          case 40: break;
          case 15:
            { return token(TokenType.SINGLE_LINE_COMMENT, yytext());
            }
          // fall through
          case 41: break;
          case 16:
            { commentStartLine = yyline + 1;
    commentDepth = 1;
    commentBuffer.setLength(0);
    commentBuffer.append(yytext());
    yybegin(COMMENT);
            }
          // fall through
          case 42: break;
          case 17:
            { commentDepth++;
    commentBuffer.append(yytext());
            }
          // fall through
          case 43: break;
          case 18:
            { commentDepth--;
    commentBuffer.append(yytext());
    if (commentDepth == 0) {
        int endLine = yyline + 1;
        yybegin(YYINITIAL);
        return token(TokenType.MULTI_LINE_COMMENT, commentBuffer.toString(), endLine);
    }
            }
          // fall through
          case 44: break;
          case 19:
            { stringBuffer.append("\"");
            }
          // fall through
          case 45: break;
          case 20:
            { stringBuffer.append("\\");
            }
          // fall through
          case 46: break;
          case 21:
            { stringBuffer.append("\n");
            }
          // fall through
          case 47: break;
          case 22:
            { stringBuffer.append("\r");
            }
          // fall through
          case 48: break;
          case 23:
            { stringBuffer.append("\t");
            }
          // fall through
          case 49: break;
          case 24:
            { return token(TokenType.CHAR_LITERAL, yytext());
            }
          // fall through
          case 50: break;
          case 25:
            { return token(TokenType.FLOAT_LITERAL, yytext());
            }
          // fall through
          case 51: break;
          case 26:
            { return token(TokenType.BOOLEAN_EXPRESSION, yytext());
            }
          // fall through
          case 52: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
